[versions]
# The Version of this project, aka, The Aya Theorem Prover.
# Remove "-SNAPSHOT" suffix and run gradle publish to release a new version.
# After that, increase the version number and add "-SNAPSHOT" suffix back for next cycle.
project = "0.40.0-SNAPSHOT"

# https://openjdk.org/
java = "25"
# https://github.com/JetBrains/java-annotations
annotations = "26.0.2"
# https://github.com/Glavo/kala-common
kala = "0.82.0"
# https://picocli.info
picocli = "4.7.7"
# https://repo1.maven.org/maven2/org/aya-prover/upstream/build-util
aya-upstream = "0.0.39"
# https://github.com/jline/jline3
jline = "3.30.6"
# http://junit.org/junit5
junit = "5.14.0-RC1"
hamcrest = "2.2"
# https://github.com/google/gson
gson = "2.13.2"
# https://github.com/beryx/badass-jlink-plugin
jlink = "3.1.3"
# https://github.com/jacoco/jacoco
jacoco = "0.8.14"

[plugins]
jlink = { id = "org.beryx.jlink", version.ref = "jlink" }

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

aya-ij-core = { group = "org.aya-prover.upstream", name = "ij-parsing-core", version.ref = "aya-upstream" }
aya-ij-text = { group = "org.aya-prover.upstream", name = "ij-util-text", version.ref = "aya-upstream" }
aya-ij-wrapper = { group = "org.aya-prover.upstream", name = "ij-parsing-wrapper", version.ref = "aya-upstream" }
aya-lsp-protocol = { group = "org.aya-prover.upstream", name = "javacs-protocol", version.ref = "aya-upstream" }
aya-build-util = { group = "org.aya-prover.upstream", name = "build-util", version.ref = "aya-upstream" }
aya-build-jflex = { group = "org.aya-prover.upstream", name = "build-util-jflex", version.ref = "aya-upstream" }
aya-jbmd-ext = { group = "org.aya-prover.upstream", name = "jb-md-ij", version.ref = "aya-upstream" }

kala-base = { group = "org.glavo.kala", name = "kala-base", version.ref = "kala" }
kala-collection = { group = "org.glavo.kala", name = "kala-collection", version.ref = "kala" }
kala-common = { group = "org.glavo.kala", name = "kala-common", version.ref = "kala" }
kala-gson = { group = "org.glavo.kala", name = "kala-common-gson", version.ref = "kala" }

picocli-runtime = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
picocli-codegen = { group = "info.picocli", name = "picocli-codegen", version.ref = "picocli" }

jline-terminal-native = { group = "org.jline", name = "jline-terminal-ffm", version.ref = "jline" }
jline-terminal-api = { group = "org.jline", name = "jline-terminal", version.ref = "jline" }
jline-builtins = { group = "org.jline", name = "jline-builtins", version.ref = "jline" }
jline-reader = { group = "org.jline", name = "jline-reader", version.ref = "jline" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
