name: Gradle Check
on: [push, pull_request]
jobs:
  gradle-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: check --info --no-daemon --stacktrace
