name: Gradle Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  gradle-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: githubActions --info --no-daemon --stacktrace --warning-mode all
      - uses: actions/upload-artifact@master
        with:
          name: nightly-build
          path : "build/*.jar"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.repository == 'aya-prover/aya-dev'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports/
          path_to_write_report: ./build/codecov_report.txt
          verbose: true
